platform :ios, '9.0'

target 'TemperatureProject' do

  pod 'Masonry'
  pod 'SDWebImage'
  pod 'SDWebImage/GIF'
  pod 'FMDB'
  pod 'YYModel'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'IQKeyboardManager'
  pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

end
